### ISSUE TITLE
Typos in the README of the ResNet18 example 

### ISSUE THREAD

**Issue by vopikamm** [Cambridge-ICCS/fortran-pytorch-lib#26]
When following the [README](https://github.com/Cambridge-ICCS/fortran-pytorch-lib/blob/main/examples/1_ResNet18/README.md) of the ResNet18 example I found some typos in the instructions.

**Comment by jatkinson1000** [comment]
Thanks for this, it's great to have someone testing!
Is there any chance you can let us know how you resolved this and open a PR?
