### ISSUE TITLE
Incompatible C++ compiler standard

### ISSUE THREAD

**Issue by ElliottKasoar** [Cambridge-ICCS/fortran-pytorch-lib#34]
When running `make` following the installation instructions in README.md, an error is raised:

```
libtorch/include/ATen/ATen.h:4:2: error: #error C++17 or later compatible compiler is required to use ATen.
```

This error was reproduced using both the [CPU-only nightly](https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip) (accessed on 19/09/23) and [CPU-only (stable) 2.0.1](https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-2.0.1%2Bcpu.zip) libtorch binaries.

This appears to be due to pytorch now [requiring support for C++17](https://github.com/pytorch/pytorch#prerequisites):
> A compiler that fully supports C++17, such as clang or gcc (especially for aarch64, gcc 9.4.0 or newer is required)

Versions used:
- cmake: 3.16.3
- gcc:  9.4.0

**Comment by jatkinson1000** [comment]
Thanks Elliott.
Did you manage to get this to work in an updated C++ minimum environment?
If so might be worth a PR to keep us up to date. Can you do this?

Also an update to the README to make it clear to users that they need to select the appropriate binary for their system if downloading libtorch.
